--------------------------------------------------------
-- Insercion de datos con procedimientos alamcenados --
--------------------------------------------------------

-- RUTAS --
DELIMITER //
CREATE PROCEDURE AGREGAR_RUTAS
(IN EST BOOLEAN, IN NOM VARCHAR(30))
BEGIN
	INSERT INTO `rutas` (`est_ruta`, `nom_ruta`) 
    VALUES(EST, NOM);
END //

CALL AGREGAR_RUTAS(1,'A023');
CALL AGREGAR_RUTAS(1,'B054');

SELECT * FROM RUTAS;


-- DISTRITOS --
DELIMITER //
CREATE PROCEDURE AGREGAR_DISTRITOS
(IN EST BOOLEAN, IN NOM VARCHAR(30))
BEGIN
 INSERT INTO DISTRITOS(EST_DIS, NOM_DIS)
 VALUES(EST, NOM);
END //

CALL AGREGAR_DISTRITOS(1,'SANTA ANITA');
CALL AGREGAR_DISTRITOS(1,'ATE');
CALL AGREGAR_DISTRITOS(1,'EL AGUSTINO');
CALL AGREGAR_DISTRITOS(1,'LA VICTORIA');

SELECT * FROM DISTRITOS;

-- PARADEROS --
DELIMITER //
CREATE PROCEDURE AGREGAR_PARADEROS
(IN EST BOOLEAN, IN NOM VARCHAR(30), IN DIS INT)
BEGIN
	INSERT INTO PARADEROS(EST_PAR, NOM_PAR, DIS_ID) 
    VALUES (EST, NOM, DIS);
END //

CALL AGREGAR_PARADEROS(1,'Puente Santa Anita',1);
CALL AGREGAR_PARADEROS(1,'Perales',1);
CALL AGREGAR_PARADEROS(1,'Ovalo Santa Anita',1);
CALL AGREGAR_PARADEROS(1,'Mall de Santa Anita',1);

SELECT * FROM PARADEROS;

-- RP --
DELIMITER //
CREATE PROCEDURE AGREGAR_RP
(IN EST BOOLEAN, IN ORDEN INT, IN PARADERO INT , IN RUTA INT)
BEGIN 
	INSERT INTO RP(EST_RP, ORDEN_RP, PAR_ID, RUTA_ID)
    VALUES(EST, ORDEN, PARADERO, RUTA);
END //

CALL AGREGAR_RP(1, 1, 1, 1);
CALL AGREGAR_RP(1, 2, 4, 1);
CALL AGREGAR_RP(1, 3, 2, 1);
CALL AGREGAR_RP(1, 1, 1, 2);
CALL AGREGAR_RP(1, 2, 4, 2);
CALL AGREGAR_RP(1, 3, 3, 2);

SELECT * FROM RP;

-- ROLES --
DELIMITER //
CREATE PROCEDURE AGREGAR_ROLES
(IN EST BOOLEAN, IN NOM VARCHAR(30))
BEGIN
	INSERT  INTO ROLES(EST_ROL, NOM_ROL)
    VALUES(EST, NOM);
END //

CALL AGREGAR_ROLES(1,'ADMINISTRADOR');
CALL AGREGAR_ROLES(1,'CONDUCTOR');

SELECT * FROM ROLES;

-- USUARIOS --
DELIMITER // 
CREATE PROCEDURE AGREGAR_USUARIO
(IN EST BOOLEAN, IN  NOMU VARCHAR(30), IN PASS VARCHAR(30), IN ROL INT)
BEGIN
	INSERT INTO USUARIOS(EST_USU, USER_USU, PASS_USU, ROL_ID)
    VALUES(EST, NOMU, PASS, ROL);
END //

CALL AGREGAR_USUARIO(1,'ADMIN','2121',1);
CALL AGREGAR_USUARIO(1,'RAULY2','E12FD',2);
CALL AGREGAR_USUARIO(1,'MAUIRO','2015DOS',2);

SELECT * FROM USUARIOS;

-- EMPRESAS --
DELIMITER //
CREATE PROCEDURE AGREGAR_EMPRESAS
(IN EST BOOLEAN, IN NOM VARCHAR(30))
BEGIN
	INSERT INTO EMPRESAS(EST_EMP, NOM_EMP)
    VALUES(EST, NOM);
END //

CALL AGREGAR_EMPRESAS(1,'SurfaceItn');
CALL AGREGAR_EMPRESAS(1,'IMPORTPERIO');

SELECT * FROM EMPRESAS;
