

--------------------------------------------------------
-- Procedimientos alamcenados --
--------------------------------------------------------

-- EMPRESAS --
DELIMITER //
CREATE PROCEDURE AGREGAR_EMPRESAS
(IN NOM VARCHAR(30), IN EST BOOLEAN)
BEGIN
	INSERT INTO empresas(NOM_EMP, EST_EMP)
    VALUES(NOM, EST);
END //


-- RUTAS --
DELIMITER //
CREATE PROCEDURE AGREGAR_RUTAS
(IN NOM VARCHAR(30), IN EST BOOLEAN, IN EMPRESA INT)
BEGIN
	INSERT INTO rutas (NOM_RUTA,EST_RUTA,EMP_ID) 
    VALUES(NOM, EST, EMPRESA);
END //

-- DISTRITOS --
DELIMITER //
CREATE PROCEDURE AGREGAR_DISTRITOS
(IN NOM VARCHAR(30), IN EST BOOLEAN)
BEGIN
 INSERT INTO distritos(NOM_DIS, EST_DIS)
 VALUES(NOM, EST);
END //

-- PARADEROS --
DELIMITER //
CREATE PROCEDURE AGREGAR_PARADEROS
(IN EST BOOLEAN, IN NOM VARCHAR(30), IN DIS INT)
BEGIN
	INSERT INTO paraderos(EST_PAR, NOM_PAR, DIS_ID) 
    VALUES (EST, NOM, DIS);
END //

-- RP --
DELIMITER //
CREATE PROCEDURE AGREGAR_RP
(IN EST BOOLEAN, IN ORDEN INT, IN PARADERO INT , IN RUTA INT)
BEGIN 
	INSERT INTO rp(EST_RP, ORDEN_RP, PAR_ID, RUTA_ID)
    VALUES(EST, ORDEN, PARADERO, RUTA);
END //

-- ROLES --
DELIMITER //
CREATE PROCEDURE AGREGAR_ROLES
(IN EST BOOLEAN, IN NOM VARCHAR(30))
BEGIN
	INSERT  INTO roles(EST_ROL, NOM_ROL)
    VALUES(EST, NOM);
END //


-- TRABAJADORES --
DELIMITER //
CREATE PROCEDURE AGREGAR_TRABAJADORES
(IN NOM VARCHAR(30), IN APE VARCHAR(30), IN DNI VARCHAR(30), IN EST BOOLEAN ,IN USUARIO VARCHAR(30), 
IN PASSW VARCHAR(30), IN ROL INT, IN EMPRESA INT)
BEGIN
	INSERT INTO trabajadores(NOM_TRA, APE_TRA, DNI_TRA, EST_TRA, USER_TRA, PASS_TRA, ROL_ID, EMPRESA_ID)
    VALUES(NOM, APE, DNI,EST, USUARIO, PASSW,ROL, EMPRESA);
END //

-- BUSES --
DELIMITER //
CREATE PROCEDURE AGREGAR_BUSES
(IN EST BOOLEAN, IN MODELO VARCHAR(30), IN PLACA VARCHAR(30), IN EMPRESA INT, IN RUTA INT, IN TRABAJADOR INT)
BEGIN
	INSERT INTO buses(EST_BUS, MOD_BUS, PLACA_BUS, EMP_ID, RUTA_ID, TRABAJADOR_ID)
    VALUES(EST, MODELO, PLACA, EMPRESA, RUTA, TRABAJADOR);
END //

-- EMPRESAS --
DELIMITER //
CREATE PROCEDURE EMPRESASH
(IN ESTADO BOOLEAN)
BEGIN
	SELECT * FROM empresas 
	WHERE EST_EMP = ESTADO;
END //

DELIMITER //
CREATE PROCEDURE LISTAR_PARADEROS_DE_RUTA_IDA(IN RUTA INT)
BEGIN
	SELECT RP.ORDEN_RP, R.NOM_RUTA, P.NOM_PAR, D.NOM_DIS
	FROM rp RP
	INNER JOIN rutas R ON RP.RUTA_ID = R.ID_RUTA
	INNER JOIN paraderos P ON RP.PAR_ID = P.ID_PAR
	INNER JOIN distritos D ON P.DIS_ID = D.ID_DIS
	WHERE R.ID_RUTA = RUTA
	ORDER BY RP.ORDEN_RP ASC;
END //


DELIMITER //
CREATE PROCEDURE LISTAR_PARADEROS_DE_RUTA_VUELTA(IN RUTA INT)
BEGIN
	SELECT RP.ORDEN_RP, R.NOM_RUTA, P.NOM_PAR, D.NOM_DIS
	FROM rp RP
	INNER JOIN rutas R ON RP.RUTA_ID = R.ID_RUTA
	INNER JOIN paraderos P ON RP.PAR_ID = P.ID_PAR
	INNER JOIN distritos D ON P.DIS_ID = D.ID_DIS
	WHERE R.ID_RUTA = RUTA
	ORDER BY RP.ORDEN_RP DESC;
END //



----- Buses -------
DELIMITER //
CREATE PROCEDURE BUSESXEMPT
(IN EMPRESA BIGINT)
BEGIN
	SELECT B.ID_BUS, R.ID_RUTA, R.NOM_RUTA, B.PLACA_BUS, B.MOD_BUS, T.ID_TRA, T.NOM_TRA, T.APE_TRA, B.EST_BUS , E.ID_EMP, E.NOM_EMP 
	FROM buses B 
	INNER JOIN rutas R ON B.RUTA_ID = R.ID_RUTA
	INNER JOIN trabajadores T ON B.TRABAJADOR_ID = T.ID_TRA
    INNER JOIN empresas E ON E.ID_EMP = B.EMP_ID
	WHERE B.EMP_ID = EMPRESA
    ORDER BY B.ID_BUS ASC;
END //

DELIMITER //
CREATE PROCEDURE BUSESXEMPH
(IN ESTADO BOOLEAN , IN EMPRESA BIGINT)
BEGIN
	SELECT B.ID_BUS, R.ID_RUTA, R.NOM_RUTA, B.PLACA_BUS, B.MOD_BUS, T.ID_TRA, T.NOM_TRA, T.APE_TRA, B.EST_BUS , E.ID_EMP, E.NOM_EMP 
	FROM buses B 
	INNER JOIN rutas R ON B.RUTA_ID = R.ID_RUTA
	INNER JOIN trabajadores T ON B.TRABAJADOR_ID = T.ID_TRA
    INNER JOIN empresas E ON E.ID_EMP = B.EMP_ID
	WHERE B.EMP_ID = EMPRESA AND B.EST_BUS = ESTADO
	ORDER BY B.ID_BUS ASC;
END //


DELIMITER //
CREATE PROCEDURE BUSESXEMPD
(IN EMPRESA BIGINT)
BEGIN
	SELECT B.ID_BUS, R.ID_RUTA, R.NOM_RUTA, B.PLACA_BUS, B.MOD_BUS, T.ID_TRA, T.NOM_TRA, T.APE_TRA, B.EST_BUS , E.ID_EMP, E.NOM_EMP 
	FROM buses B 
	INNER JOIN rutas R ON B.RUTA_ID = R.ID_RUTA
	INNER JOIN trabajadores T ON B.TRABAJADOR_ID = T.ID_TRA
    INNER JOIN empresas E ON E.ID_EMP = B.EMP_ID
	WHERE B.EMP_ID = EMPRESA AND B.EST_BUS = 0
	ORDER BY B.ID_BUS ASC;
END //

----- Trabajadores -------
DELIMITER //
CREATE PROCEDURE TRABAJADORXEMPT
(IN EMPRESA INT)
BEGIN
	SELECT T.ID_TRA, T.NOM_TRA, T.APE_TRA,T.DNI_TRA , E.ID_EMP, E.NOM_EMP, T.USER_TRA, T.PASS_TRA, R.ID_ROL, R.NOM_ROL, T.EST_TRA
	FROM trabajadores T
	INNER JOIN roles R ON R.ID_ROL = T.ROL_ID 
	INNER JOIN empresas E ON T.EMPRESA_ID = E.ID_EMP
	WHERE E.ID_EMP = EMPRESA
	ORDER BY T.ID_TRA ASC;
END //

DELIMITER //
CREATE PROCEDURE TRABAJADORXEMPH
(IN ESTADO BOOLEAN, IN EMPRESA INT)
BEGIN
	SELECT T.ID_TRA, T.NOM_TRA, T.APE_TRA,T.DNI_TRA , E.ID_EMP, E.NOM_EMP, T.USER_TRA, T.PASS_TRA, R.ID_ROL, R.NOM_ROL, T.EST_TRA
	FROM trabajadores T
	INNER JOIN roles R ON R.ID_ROL = T.ROL_ID 
	INNER JOIN empresas E ON T.EMPRESA_ID = E.ID_EMP
	WHERE E.ID_EMP = EMPRESA AND T.EST_TRA = ESTADO
    ORDER BY T.ID_TRA ASC;
END //

DELIMITER //
CREATE PROCEDURE TRABAJADORXEMPR
(IN EMPRESA INT, IN ESTADO BOOLEAN, IN ROL INT)
BEGIN
	SELECT T.ID_TRA, T.NOM_TRA, T.APE_TRA,T.DNI_TRA , E.ID_EMP, E.NOM_EMP, T.USER_TRA, T.PASS_TRA, R.ID_ROL, R.NOM_ROL, T.EST_TRA
	FROM trabajadores T
	INNER JOIN roles R ON R.ID_ROL = T.ROL_ID 
	INNER JOIN empresas E ON T.EMPRESA_ID = E.ID_EMP
	WHERE E.ID_EMP = EMPRESA AND T.EST_TRA = ESTADO AND R.ID_ROL = ROL
	ORDER BY T.ID_TRA ASC;
END //

DELIMITER //
CREATE PROCEDURE ROLESXH
(IN EST INT)
BEGIN
	SELECT ID_ROL, NOM_ROL, EST_ROL
    FROM roles
    WHERE EST_ROL = EST
    ORDER BY ID_ROL ASC;
END //



----- RUTAS -----
DELIMITER //
CREATE PROCEDURE RUTASXEMPT
(IN EMPRESA INT)
BEGIN
	SELECT R.ID_RUTA, R.NOM_RUTA, E.NOM_EMP, R.EST_RUTA
    FROM rutas R
	INNER JOIN empresas E ON R.EMP_ID = E.ID_EMP
	WHERE R.EMP_ID = EMPRESA;
END //

DELIMITER //
CREATE PROCEDURE RUTASXEMPH
(IN EMPRESA INT)
BEGIN
	SELECT R.ID_RUTA, R.NOM_RUTA, E.NOM_EMP, R.EST_RUTA
    FROM rutas R
	INNER JOIN empresas E ON R.EMP_ID = E.ID_EMP
	WHERE R.EMP_ID = EMPRESA AND EST_RUTA = TRUE;
END //

DELIMITER //
CREATE PROCEDURE RUTASXEMPD
(IN EMPRESA INT)
BEGIN
	SELECT R.ID_RUTA, R.NOM_RUTA, E.NOM_EMP, R.EST_RUTA
    FROM rutas R
	INNER JOIN empresas E ON R.EMP_ID = E.ID_EMP
	WHERE R.EMP_ID = EMPRESA AND EST_RUTA = FALSE;
END //

----- DISTRITOS -----
DELIMITER //
CREATE PROCEDURE DIST
(IN EMPRESA INT)
BEGIN
	SELECT * FROM distritos;
END //

DELIMITER //
CREATE PROCEDURE DISH
(IN EST BOOLEAN)
BEGIN
	SELECT * FROM distritos
	WHERE EST_DIS = EST;
	END //

DELIMITER //
CREATE PROCEDURE PARH
(IN EST BOOLEAN)
BEGIN
	SELECT P.ID_PAR, P.NOM_PAR, D.ID_DIS, D.NOM_DIS, P.LONGITUD, P.LATITUD, P.EST_PAR FROM paraderos P
    INNER JOIN distritos D
	ON P.DIS_ID = D.ID_DIS
    WHERE P.EST_PAR = EST
    ORDER BY P.EST_PAR ASC;
END //

--------------------------------------------------------
-- Creacion de vistas --
--------------------------------------------------------
CREATE VIEW LISTBUSESD
AS
SELECT B.ID_BUS, R.ID_RUTA,  R.NOM_RUTA, B.PLACA_BUS, B.MOD_BUS, T.NOM_TRA, T.APE_TRA, E.NOM_EMP, B.LATITUD, B.LONGITUD
FROM buses B
INNER JOIN trabajadores T ON B.TRABAJADOR_ID = T.ID_TRA
INNER JOIN empresas E ON B.EMP_ID = E.ID_EMP
INNER JOIN rutas R ON B.RUTA_ID = R.ID_RUTA
ORDER BY B.ID_BUS ASC;

CREATE VIEW EMPRESAS_HABILITADAS
AS
SELECT * FROM empresas 
WHERE EST_EMP = 1;

CREATE VIEW EMPRESAS_DESHABILITADAS
AS
SELECT * FROM empresas 
WHERE EST_EMP = 0;





DELIMITER //
CREATE PROCEDURE PARADEROXRUTA
(IN RUTA INT)
BEGIN
SELECT RP.ID_RP, RP.ORDEN_RP,R.ID_RUTA,  R.NOM_RUTA, P.ID_PAR, P.NOM_PAR, D.ID_DIS, D.NOM_DIS, P.LATITUD, P.LONGITUD, RP.EST_RP
FROM rp RP
	INNER JOIN rutas R ON RP.RUTA_ID = R.ID_RUTA
	INNER JOIN paraderos P ON RP.PAR_ID = P.ID_PAR
	INNER JOIN distritos D ON P.DIS_ID = D.ID_DIS
	WHERE R.ID_RUTA = RUTA 
    ORDER BY P.LONGITUD ASC;
END //

-- CALL PARADEROXRUTA(4);






