drop database bateriacamiondb;
create database bateriacamiondb;

SELECT * FROM EMPRESAS;
SELECT * FROM RUTAS;
SELECT * FROM DISTRITOS;
SELECT * FROM PARADEROS;
SELECT * FROM RP;
SELECT * FROM ROLES;
SELECT * FROM TRABAJADORES;
SELECT * FROM BUSES;

-- Nuevo
select * from trabajadores_roles;
SELECT * FROM ROLESu;

SELECT RP.ID_RP, RP.ORDEN_RP, R.NOM_RUTA, P.NOM_PAR, D.NOM_DIS, P.LATITUD, P.LONGITUD FROM RP
INNER JOIN RUTAS R ON RP.RUTA_ID = R.ID_RUTA
INNER JOIN PARADEROS P ON RP.RUTA_ID = P.ID_PAR
INNER JOIN DISTRITOS D ON P.DIS_ID = D.ID_DIS;


SELECT RP.ID_RP, RP.ORDEN_RP,R.ID_RUTA,  R.NOM_RUTA, P.ID_PAR, P.NOM_PAR, D.ID_DIS, D.NOM_DIS, P.LATITUD, P.LONGITUD, RP.EST_RP 
FROM RP
INNER JOIN RUTAS R ON RP.RUTA_ID = R.ID_RUTA
INNER JOIN PARADEROS P ON RP.RUTA_ID = P.ID_PAR
INNER JOIN DISTRITOS D ON P.DIS_ID = D.ID_DIS
WHERE RP.RUTA_ID = 2;



SELECT RP.ID_RP, RP.ORDEN_RP,R.ID_RUTA,  R.NOM_RUTA, P.ID_PAR, P.NOM_PAR, D.ID_DIS, D.NOM_DIS, P.LATITUD, P.LONGITUD, RP.EST_RP 
FROM RP
INNER JOIN RUTAS R ON RP.RUTA_ID = R.ID_RUTA
INNER JOIN PARADEROS P ON RP.PAR_ID = P.ID_PAR
INNER JOIN DISTRITOS D ON P.DIS_ID = D.ID_DIS
WHERE RP.RUTA_ID = 3
ORDER BY P.LONGITUD ASC


SELECT RP.ID_RP, RP.ORDEN_RP,R.ID_RUTA,  R.NOM_RUTA, P.ID_PAR, P.NOM_PAR FROM RP
INNER JOIN RUTAS R ON RP.RUTA_ID = R.ID_RUTA
INNER JOIN PARADEROS P ON RP.PAR_ID = P.ID_PAR
INNER JOIN DISTRITOS D ON P.DIS_ID = D.ID_DIS
WHERE RP.RUTA_ID = 2;

